### ISSUE TITLE
could you share your template formats for prometheus output for ClickHouse predefined query HTTP handlers?

### ISSUE THREAD

**Issue by Slach** [TCeason/TCeason#1]
You are author of 
following code https://github.com/ClickHouse/ClickHouse/commit/214c465b535e45c7d11759154930bb9a9b0dfbb8#diff-36f657a91dc754a86e90bcc56df6003270fca8d7c83f5cb6f2de72c871c5b51aR301 in clickhouse documentation

Could you share configs related with?
```
prometheus_template_output_format_resultset 
prometheus_template_output_format_row
```
?

**Comment by TCeason** [comment]
> You are author of following code [ClickHouse/ClickHouse@214c465#diff-36f657a91dc754a86e90bcc56df6003270fca8d7c83f5cb6f2de72c871c5b51aR301](https://github.com/ClickHouse/ClickHouse/commit/214c465b535e45c7d11759154930bb9a9b0dfbb8#diff-36f657a91dc754a86e90bcc56df6003270fca8d7c83f5cb6f2de72c871c5b51aR301) in clickhouse documentation
> 
> Could you share configs related with?
> 
> ```
> prometheus_template_output_format_resultset 
> prometheus_template_output_format_row
> ```
> 
> ?

In my mind these configs can be set in config.xml. And in this doc, that just a name. In my memory, the config is in a ck issue.
